FROM node:10
COPY ./ /crestui
WORKDIR /crestui

RUN npm install && npm rebuild node-sass && npm update caniuse-lite browserslist && npm run cern-build

FROM nginx
RUN mkdir /crestui
COPY --from=0 /crestui/dist /etc/nginx/html/crestui
COPY nginx.conf /etc/nginx/nginx.conf
