package hep.crest.data.pojo;
// Generated Aug 2, 2016 3:50:25 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GlobalTagMapId generated by hbm2java
 */
@Embeddable
public class GlobalTagMapId implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = -2041411292811311312L;
	private String globalTagName;
	private String record;
	private String label;

	public GlobalTagMapId() {
	}

	public GlobalTagMapId(String globalTagName, String record, String label) {
		this.globalTagName = globalTagName;
		this.record = record;
		this.label = label;
	}

	@Column(name = "GLOBAL_TAG_NAME", nullable = false, length = 100)
	public String getGlobalTagName() {
		return this.globalTagName;
	}

	public void setGlobalTagName(String globalTagName) {
		this.globalTagName = globalTagName;
	}

	@Column(name = "RECORD", nullable = false, length = 100)
	public String getRecord() {
		return this.record;
	}

	public void setRecord(String record) {
		this.record = record;
	}

	@Column(name = "LABEL", nullable = false, length = 100)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GlobalTagMapId))
			return false;
		GlobalTagMapId castOther = (GlobalTagMapId) other;

		return ((this.getGlobalTagName() == castOther.getGlobalTagName())
				|| (this.getGlobalTagName() != null && castOther.getGlobalTagName() != null
						&& this.getGlobalTagName().equals(castOther.getGlobalTagName())))
				&& ((this.getRecord() == castOther.getRecord()) || (this.getRecord() != null
						&& castOther.getRecord() != null && this.getRecord().equals(castOther.getRecord())))
				&& ((this.getLabel() == castOther.getLabel()) || (this.getLabel() != null
						&& castOther.getLabel() != null && this.getLabel().equals(castOther.getLabel())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getGlobalTagName() == null ? 0 : this.getGlobalTagName().hashCode());
		result = 37 * result + (getRecord() == null ? 0 : this.getRecord().hashCode());
		result = 37 * result + (getLabel() == null ? 0 : this.getLabel().hashCode());
		return result;
	}

}
