package hep.crest.data.pojo;
// Generated Aug 2, 2016 3:50:25 PM by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IovId generated by hbm2java
 */
@Embeddable
public class IovId implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = -2770785371714771938L;
	private Long tagid;
	private BigDecimal since;
	private Date insertionTime;

	public IovId() {
	}

	public IovId(Long tagid, BigDecimal since, Date insertionTime) {
		this.tagid = tagid;
		this.since = since;
		this.insertionTime = insertionTime;
	}

	@Column(name = "TAG_ID", nullable = false, precision = 20, scale = 0)
	public Long getTagid() {
		return this.tagid;
	}

	public void setTagid(Long tagid) {
		this.tagid = tagid;
	}

	@Column(name = "SINCE", nullable = false, precision = 38, scale = 0)
	public BigDecimal getSince() {
		return this.since;
	}

	public void setSince(BigDecimal since) {
		this.since = since;
	}

	@Column(name = "INSERTION_TIME", nullable = false, length = 11)
	public Date getInsertionTime() {
		return this.insertionTime;
	}

	public void setInsertionTime(Date insertionTime) {
		this.insertionTime = insertionTime;
	}


	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		IovId other = (IovId) obj;
		if (insertionTime == null) {
			if (other.insertionTime != null)
				return false;
		} else if (!insertionTime.equals(other.insertionTime))
			return false;
		if (since == null) {
			if (other.since != null)
				return false;
		} else if (!since.equals(other.since))
			return false;
		if (tagid == null) {
			if (other.tagid != null)
				return false;
		} else if (!tagid.equals(other.tagid))
			return false;
		return true;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((insertionTime == null) ? 0 : insertionTime.hashCode());
		result = prime * result + ((since == null) ? 0 : since.hashCode());
		result = prime * result + ((tagid == null) ? 0 : tagid.hashCode());
		return result;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "IovId [tagid=" + tagid + ", since=" + since + ", insertionTime=" + insertionTime + "]";
	}

}
