package hep.crest.data.pojo;
// Generated Aug 2, 2016 3:50:25 PM by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IovId generated by hbm2java.
 */
@Embeddable
public class IovId implements java.io.Serializable {
    /**
     * Serializer.
     */
    private static final long serialVersionUID = -2770785371714771938L;
    /**
     * The tag name.
     */
    private String tagName;
    /**
     * The since time.
     */
    private BigDecimal since;
    /**
     * The insertion time.
     */
    private Date insertionTime;

    /**
     * Default ctor.
     */
    public IovId() {
    }

    /**
     * Complete ctor.
     * 
     * @param tagName
     *            the String
     * @param since
     *            the BigDecimal
     * @param insertionTime
     *            the Date
     */
    public IovId(String tagName, BigDecimal since, Date insertionTime) {
        this.tagName = tagName;
        this.since = since;
        this.insertionTime = insertionTime;
    }

    /**
     * @return String
     */
    @Column(name = "TAG_NAME", nullable = false, length = 255)
    public String getTagName() {
        return this.tagName;
    }

    /**
     * @param tagName
     *            the String
     * @return
     */
    public void setTagName(String tagName) {
        this.tagName = tagName;
    }

    /**
     * @return BigDecimal
     */
    @Column(name = "SINCE", nullable = false, precision = 38, scale = 0)
    public BigDecimal getSince() {
        return this.since;
    }

    /**
     * @param since
     *            the BigDecimal
     * @return
     */
    public void setSince(BigDecimal since) {
        this.since = since;
    }

    /**
     * @return Date
     */
    @Column(name = "INSERTION_TIME", nullable = false, length = 11)
    public Date getInsertionTime() {
        return this.insertionTime;
    }

    /**
     * @param insertionTime
     *            the Date
     * @return
     */
    public void setInsertionTime(Date insertionTime) {
        this.insertionTime = insertionTime;
    }

    /*
     * (non-Javadoc)
     *
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (other == null) {
            return false;
        }
        if (!(other instanceof IovId)) {
            return false;
        }
        final IovId castOther = (IovId) other;

        return (this.getTagName() == castOther.getTagName()
                || this.getTagName() != null && castOther.getTagName() != null
                        && this.getTagName().equals(castOther.getTagName()))
                && (this.getSince() == castOther.getSince()
                        || this.getSince() != null && castOther.getSince() != null
                                && this.getSince().equals(castOther.getSince()))
                && (this.getInsertionTime() == castOther.getInsertionTime()
                        || this.getInsertionTime() != null && castOther.getInsertionTime() != null
                                && this.getInsertionTime().equals(castOther.getInsertionTime()));
    }

    /*
     * (non-Javadoc)
     *
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + (getTagName() == null ? 0 : this.getTagName().hashCode());
        result = 37 * result + (getSince() == null ? 0 : this.getSince().hashCode());
        result = 37 * result
                + (getInsertionTime() == null ? 0 : this.getInsertionTime().hashCode());
        return result;
    }

    /*
     * (non-Javadoc)
     *
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return "IovId [tagName=" + tagName + ", since=" + since + ", insertionTime=" + insertionTime
                + "]";
    }
}
