package hep.crest.data.pojo;
// Generated Aug 2, 2016 3:50:25 PM by Hibernate Tools 3.2.2.GA

import java.sql.Blob;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Type;

import hep.crest.data.config.DatabasePropertyConfigurator;

/**
 * Payload generated by hbm2java.
 */
@Entity
@Table(name = "PAYLOAD", schema = DatabasePropertyConfigurator.SCHEMA_NAME)
public class Payload implements java.io.Serializable {
    /**
     * Serializer.
     */
    private static final long serialVersionUID = 5486724556389838782L;
    /**
     * The hash.
     */
    private String hash;
    /**
     * The version.
     */
    private String version;
    /**
     * The object type.
     */
    private String objectType;
    /**
     * The size.
     */
    private Integer size;
    /**
     * The data blob. It will be transformed in a stream or byte array.
     */
    private Blob data;
    /**
     * The streamer info blob.
     */
    private Blob streamerInfo;
    /**
     * The insertion time.
     */
    private Date insertionTime;

    /**
     * Default ctor.
     */
    public Payload() {
    }

    /**
     * Ctor.
     * 
     * @param hash
     *            the String
     * @param objectType
     *            the String
     * @param data
     *            the Blob
     * @param streamerInfo
     *            the Blob
     * @param insertionTime
     *            the Date
     */
    public Payload(String hash, String objectType, Blob data, Blob streamerInfo,
            Date insertionTime) {
        this.hash = hash;
        this.objectType = objectType;
        this.data = data;
        this.streamerInfo = streamerInfo;
        this.insertionTime = insertionTime;
    }

    /**
     * @return String
     */
    @Id
    @Column(name = "HASH", unique = true, nullable = false, length = 64)
    public String getHash() {
        return this.hash;
    }

    /**
     * @param hash
     *            the String
     * @return
     */
    public void setHash(String hash) {
        this.hash = hash;
    }

    ////// @/////Version
    /**
     * @return String
     */
    @Column(name = "VERSION", nullable = false, length = 20)
    public String getVersion() {
        return this.version;
    }

    /**
     * @param version the String
     * @return
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * @return String
     */
    @Column(name = "OBJECT_TYPE", nullable = false, length = 100)
    public String getObjectType() {
        return this.objectType;
    }

    /**
     * @param objectType
     *            the String
     * @return
     */
    public void setObjectType(String objectType) {
        this.objectType = objectType;
    }

    /**
     * @return Integer
     */
    @Column(name = "DATA_SIZE", nullable = true)
    public Integer getSize() {
        return size;
    }

    /**
     * @param size
     *            the Integer
     * @return
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * @return Blob
     */
    @Column(name = "DATA", nullable = false)
    @Lob
    @Type(type = "org.hibernate.type.BlobType")
    public Blob getData() {
        return this.data;
    }

    /**
     * @param data
     *            the Blob
     * @return
     */
    public void setData(Blob data) {
        this.data = data;
    }

    /**
     * @return Blob
     */
    @Column(name = "STREAMER_INFO", nullable = false)
    @Lob
    @Type(type = "org.hibernate.type.BlobType")
    public Blob getStreamerInfo() {
        return this.streamerInfo;
    }

    /**
     * @param streamerInfo
     *            the Blob
     * @return
     */
    public void setStreamerInfo(Blob streamerInfo) {
        this.streamerInfo = streamerInfo;
    }

    /**
     * @return Date
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "INSERTION_TIME", nullable = false, length = 11)
    public Date getInsertionTime() {
        return this.insertionTime;
    }

    /**
     * @param insertionTime
     *            the Date
     * @return
     */
    public void setInsertionTime(Date insertionTime) {
        this.insertionTime = insertionTime;
    }

    /*
     * (non-Javadoc)
     *
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return "Payload [hash=" + hash + ", version=" + version + ", objectType=" + objectType
                + ", size=" + size + ", insertionTime=" + insertionTime + "]";
    }
}
