package hep.crest.data.pojo;
// Generated Aug 2, 2016 3:50:25 PM by Hibernate Tools 3.2.2.GA

import java.sql.Blob;
import java.sql.Timestamp;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Type;

import hep.crest.data.config.DatabasePropertyConfigurator;

/**
 * Payload generated by hbm2java
 */
@Entity
@Table(name = "TAG_META", schema = DatabasePropertyConfigurator.SCHEMA_NAME)
public class TagMeta implements java.io.Serializable {

    /**
     * The serial id.
     */
    private static final long serialVersionUID = 5486724556389838782L;
    /**
     * The tag name.
     */
    private String tagName;
    /**
     * The description.
     */
    private String description;
    /**
     * The number of channels.
     */
    private Integer chansize;
    /**
     * The number of columns in the payload.
     */
    private Integer colsize;
    /**
     * The channel list.
     */
    private Blob channelInfo;
    /**
     * The payload specifications.
     */
    private Blob payloadInfo;
    /**
     * The insertion time.
     */
    private Date insertionTime;

    /**
     * Default ctor.
     */
    public TagMeta() {
    }

    /**
     * @param tagName
     *            the String
     * @param description
     *            the String
     * @param chansize
     *            the Integer
     * @param channelInfo
     *            the Blob
     * @param payloadInfo
     *            the Blob
     */
    public TagMeta(String tagName, String description, Integer chansize, Integer colsize,
            Blob channelInfo, Blob payloadInfo) {
        super();
        this.tagName = tagName;
        this.description = description;
        this.chansize = chansize;
        this.colsize = colsize;
        this.channelInfo = channelInfo;
        this.payloadInfo = payloadInfo;
    }

    /**
     * @return the tagName
     */
    @Id
    @Column(name = "TAG_NAME", unique = true, nullable = false, length = 255)
    public String getTagName() {
        return tagName;
    }

    /**
     * @param tagName
     *            the tagName to set
     */
    public void setTagName(String tagName) {
        this.tagName = tagName;
    }

    /**
     * @return the description
     */
    public String getDescription() {
        return description;
    }

    /**
     * @param version
     *            the version to set
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * @return the chansize
     */
    @Column(name = "CHANNEL_SIZE")
    public Integer getChansize() {
        return chansize;
    }

    /**
     * @param chansize
     *            the chansize to set
     */
    public void setChansize(Integer chansize) {
        this.chansize = chansize;
    }

    /**
     * @return the colsize
     */
    @Column(name = "COLUMN_SIZE")
    public Integer getColsize() {
        return colsize;
    }

    /**
     * @param colsize
     *            the colsize to set
     */
    public void setColsize(Integer colsize) {
        this.colsize = colsize;
    }

    /**
     * @return Date
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "INSERTION_TIME", nullable = false, length = 11)
    public Date getInsertionTime() {
        return this.insertionTime;
    }

    /**
     * @param insertionTime
     *            the Date
     * @return
     */
    public void setInsertionTime(Date insertionTime) {
        this.insertionTime = insertionTime;
    }

    /**
     * @return Blob
     */
    @Column(name = "CHANNEL_INFO", nullable = false)
    @Lob
    @Type(type = "org.hibernate.type.BlobType")
    public Blob getChannelInfo() {
        return this.channelInfo;
    }

    /**
     * @param channelInfo
     *            the Blob
     * @return
     */
    public void setChannelInfo(Blob channelInfo) {
        this.channelInfo = channelInfo;
    }

    /**
     * @return Blob
     */
    @Column(name = "PAYLOAD_INFO", nullable = false)
    @Lob
    @Type(type = "org.hibernate.type.BlobType")
    public Blob getPayloadInfo() {
        return this.payloadInfo;
    }

    /**
     * @param payloadInfo
     *            the Blob
     * @return
     */
    public void setPayloadInfo(Blob payloadInfo) {
        this.payloadInfo = payloadInfo;
    }

    /**
     * 
     * @return
     */
    @PrePersist
    public void prePersist() {
        if (this.insertionTime == null) {
            final Timestamp now = new Timestamp(new Date().getTime());
            this.insertionTime = now;
        }
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return "TagMeta [tagName=" + tagName + ", description=" + description + ", chansize="
                + chansize + ", colsize=" + colsize + ", insertionTime=" + insertionTime + "]";
    }

}
