openapi: 3.0.0

info:
  $ref: 'schemas/common.yml#/info'

servers:
  $ref: 'schemas/common.yml#/servers'

security:
  $ref: 'schemas/common.yml#/security'

tags:
  - name: globaltags


paths:
  /globaltags:
    get:
      tags:
        - globaltags
      summary: Finds a GlobalTagDtos lists.
      description: |
        This method allows to perform search and sorting.
        Arguments: name=<pattern>, workflow, scenario, release, validity, description
        page={ipage}, size={isize}, sort=<sortpattern>.
      operationId: listGlobalTags
      parameters:
        - name: name
          in: query
          description: 'the global tag name search pattern {none}'
          required: false
          schema:
            type: string
            default: all
        - name: workflow
          in: query
          description: 'the global tag workflow search pattern {none}'
          required: false
          schema:
            type: string
        - name: scenario
          in: query
          description: 'the global tag scenario search pattern {none}'
          required: false
          schema:
            type: string
        - name: release
          in: query
          description: 'the global tag release search pattern {none}'
          required: false
          schema:
            type: string
        - name: validity
          in: query
          description: 'the global tag validity low limit {x>=validity}'
          required: false
          schema:
            type: integer
            format: int64
        - name: description
          in: query
          description: 'the global tag description search pattern {none}'
          required: false
          schema:
            type: string
        - name: page
          in: query
          description: 'page: the page number {0}'
          required: false
          schema:
            type: integer
            default: 0
            format: int32
        - name: size
          in: query
          description: 'size: the page size {1000}'
          required: false
          schema:
            type: integer
            default: 1000
            format: int32
        - name: sort
          in: query
          description: 'sort: the sort pattern {name:ASC}'
          required: false
          schema:
            type: string
            default: 'name:ASC'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GlobalTagSetDto"
        '404':
          $ref: "#/components/responses/404"
        default:
          $ref: "#/components/responses/genericError"
    post:
      tags:
        - globaltags
      summary: Create a GlobalTag in the database.
      description: 'This method allows to insert a GlobalTag.Arguments: GlobalTagDto should be provided in the body as a JSON file.'
      operationId: createGlobalTag
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GlobalTagDto'
      parameters:
        - name: force
          in: query
          description: 'force: tell the server if it should use or not the insertion time provided {default: false}'
          required: false
          schema:
            type: string
            default: false
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GlobalTagDto"
        default:
          $ref: "#/components/responses/genericError"
  /globaltags/{name}:
    get:
      tags:
        - globaltags
      summary: Finds a GlobalTagDto by name
      description: This method will search for a global tag with the given name. Only one global tag should be returned.
      operationId: findGlobalTag
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GlobalTagSetDto"
        '404':
          $ref: "#/components/responses/404"
        default:
          $ref: "#/components/responses/genericError"
  /globaltags/{name}/tags:
    get:
      tags:
        - globaltags
      summary: Finds a TagDtos lists associated to the global tag name in input.
      description: 'This method allows to trace a global tag.Arguments: record=<record> filter output by record, label=<label> filter output by label'
      operationId: findGlobalTagFetchTags
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
        - name: record
          in: query
          description: 'record:  the record string {}'
          required: false
          schema:
            type: string
            default: none
        - name: label
          in: query
          description: 'label:  the label string {}'
          required: false
          schema:
            type: string
            default: none
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TagSetDto"
        '404':
          $ref: "#/components/responses/404"
        default:
          $ref: "#/components/responses/genericError"
components:
  securitySchemes:
    $ref: 'schemas/common.yml#/components/securitySchemes'
  requestBodies:
    $ref: 'schemas/common.yml#/components/requestBodies'
  responses:
    $ref: 'schemas/common.yml#/components/responses'

  schemas:
    # commons
    HTTPResponse:
      $ref: 'schemas/common.yml#/components/schemas/HTTPResponse'
    CrestBaseResponse:
      $ref: 'schemas/common.yml#/components/schemas/CrestBaseResponse'
    RespPage:
      $ref: 'schemas/common.yml#/components/schemas/RespPage'
    GenericMap:
      $ref: 'schemas/common.yml#/components/schemas/GenericMap'

    TagSetDto:
      $ref: 'schemas/tags.yml#/components/schemas/TagSetDto'
    GlobalTagSetDto:
      $ref: 'schemas/globaltags.yml#/components/schemas/GlobalTagSetDto'
    GlobalTagDto:
      $ref: 'schemas/globaltags.yml#/components/schemas/GlobalTagDto'
