# ===============================
# = PROFILES /
#             server
#             ...
# ===============================
# Defaults
spring:
    config:
      use-legacy-processing: true
    profiles:
      includes: crest
    servlet:
      multipart:
        max-file-size: 50MB
        max-request-size: 50MB
    jersey:
      application-path: ${crest.api.name}
    datasource:
      url: ${crest.db.url}
      driverClassName: org.postgresql.Driver
      username: ${crest.db.user}
      password: ${crest.db.password}
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        connection-test-query: SELECT 1
        maximum-pool-size: 10
    jpa:
      properties:
        hibernate.dialect: org.hibernate.dialect.PostgreSQL9Dialect
        hibernate.jdbc.fetch_size: 300
# This should be changed for production to "validate"
        hibernate.hbm2ddl.auto: validate
        hibernate.show_sql: false
        hibernate.jdbc.use_streams_for_binary: false
        hibernate.connection.autocommit: false
        hibernate.jdbc.lob.non_contextual_creation: true
server:
    port: ${crest.server.port} 
crest:
  schemaname: none
  webstaticdir: ${crest.web.static}
  dumpdir: ${crest.dump.dir}
  security: ${crest.server.security}
  synchro: none
  authenticationtype: none
  
