# ===============================
# = PROFILES /
#             server
#             ...
# ===============================
# Defaults
spring:
    servlet:
      multipart:
        max-file-size: 200MB
        max-request-size: 400MB
    jersey:
      application-path: ${crest.api.name}
    datasource:
      main:
        jdbcUrl: ${crest.db.url}
        driverClassName: oracle.jdbc.OracleDriver
        username: ${crest.db.user}
        password: ${crest.db.password}
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
          connection-test-query: SELECT 1 FROM DUAL
          maximum-pool-size: 20
      trigger:
        jdbcUrl: ${crest.triggerdb.url}
        driverClassName: oracle.jdbc.OracleDriver
        username: ${crest.triggerdb.user}
        password: ${crest.triggerdb.password}
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
          connection-test-query: SELECT 1 FROM DUAL
          maximum-pool-size: 10
    jpa:
      properties:
        hibernate.dialect: org.hibernate.dialect.OracleDialect
        hibernate.jdbc.fetch_size: 100
        hibernate.show_sql: false
        hibernate.hbm2ddl.auto: ${jpa.mode}
        hibernate.default_schema: ${crest.db.schema}

server:
    port: ${crest.server.port}
    connection-timeout: 300s
crest:
  schemaname: ${crest.db.schema}
  webstaticdir: ${crest.web.static}
  dumpdir: ${crest.dump.dir}
  security: ${crest.server.security}
  synchro: none
  authenticationtype: none
info:
  app:
    name: Crest Application
    description: Rest services for conditions data management 
    profile: oracle
    

