caching:
    iovsgroups_maxage: 600
    iovsgroups_snapshot_maxage: 3600
    iovs_maxage: 600
    iovs_snapshot_maxage: 3600
    payloads_maxage: 604800    # expressed in seconds: 3600*24*7
    timetype_groupsize: 1000
    runtype_groupsize: 100
