package hep.crest.server.data.pojo;
// Generated Aug 2, 2016 3:50:25 PM by Hibernate Tools 3.2.2.GA

import lombok.Data;
import lombok.experimental.Accessors;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * GlobalTagMapId generated by hbm2java.
 */
// This object represents an ID and it is embedded in GlobalTagMap.
// Define default constructors.
// Define equals and hashcode methods.
// These are essential for ID comparison.
@Embeddable
@Data
@Accessors(chain = true)
public class GlobalTagMapId implements java.io.Serializable {

    /**
     * The global tag name.
     */
    @Column(name = "GLOBAL_TAG_NAME", nullable = false, length = 100)
    private String globalTagName;
    /**
     * The record. Used to identify a specific tag usage.
     */
    @Column(name = "RECORD", nullable = false, length = 100)
    private String tagRecord;
    /**
     * The label. It represents a generic tag name, similarly to COOL folder.
     */
    @Column(name = "LABEL", nullable = false, length = 100)
    private String label;

}
