package hep.crest.server.data.pojo;
// Generated Aug 2, 2016 3:50:25 PM by Hibernate Tools 3.2.2.GA

import hep.crest.server.config.DatabasePropertyConfigurator;
import lombok.Data;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Lob;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.experimental.Accessors;

import java.sql.Timestamp;
import java.time.Instant;
import java.util.Date;

/**
 * Payload generated by hbm2java.
 */
@Entity
@Table(name = "TAG_META", schema = DatabasePropertyConfigurator.SCHEMA_NAME)
@Data
@Accessors(chain = true)
@NoArgsConstructor
public class TagMeta implements java.io.Serializable {

    /**
     * The serial id.
     */
    private static final long serialVersionUID = 5486724556389838782L;
    /**
     * The tag name.
     */
    @Id
    @Column(name = "TAG_NAME", unique = true, nullable = false, length = 255)
    private String tagName;
    /**
     * The description.
     */
    @Column(name = "DESCRIPTION", nullable = false, length = 512)
    private String description;
    /**
     * The number of channels.
     */
    @Column(name = "CHANNEL_SIZE")
    private Integer chansize;
    /**
     * The number of columns in the payload.
     */
    @Column(name = "COLUMN_SIZE")
    private Integer colsize;
    /**
     * The tag info json.
     */
    @ToString.Exclude
    @Column(name = "TAG_INFO", nullable = false)
    @Lob
    private byte[] tagInfo;
    /**
     * The insertion time.
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "INSERTION_TIME", nullable = false, updatable = true, length = 11)
    private Date insertionTime;

    /**
     * 
     * @return
     */
    @PrePersist
    public void prePersist() {
        if (this.insertionTime == null) {
            final Timestamp now = Timestamp.from(Instant.now());
            this.insertionTime = now;
        }
    }
}
