#_______________________________________________________________________________
#
# Andrea Formica - October 2018
#
# Instructions to deploy VHFMGR server (taken from H.Louvin: messaging example)
#
# docker stack deploy --with-registry-auth -c docker-compose.yml svom_vhfmgr_ssl
#
#_______________________________________________________________________________

version: '3.6'

services:
  service:
    image: svomtest.svom.eu:5543/crest-service:0.2
    ports:
      - "9090:8080"
    configs:
    - source: crest-config
      target: /home/svom/application.properties
    - source: crest-logs
      target: /home/svom/logback.xml
    - source: crest-jopts
      target: /home/svom/javaopts.properties
    environment:
        - spring.profiles.active=postgres
    volumes:
        - /tmp/data/logs:/home/svom/data/logs
        - /tmp/data/web:/home/svom/data/web
        - /tmp/data/web/dump:/home/svom/data/web/dump

configs:
  crest-config:
    external: true
  crest-logs:
    external: true
  crest-jopts:
    external: true
