package hep.crest.data.runinfo.pojo;
// Generated Aug 2, 2016 3:50:25 PM by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import hep.crest.data.config.DatabasePropertyConfigurator;

/**
 * GlobalTag generated by hbm2java.
 */
@Entity
@Table(name = "RUN_INFO", schema = DatabasePropertyConfigurator.SCHEMA_NAME)
public class RunInfo implements java.io.Serializable {

    /**
     * Serializer.
     */
    private static final long serialVersionUID = 2748272207787384292L;

    /**
     * The start time of this run.
     */
    private Date startTime;
    /**
     * The end time of this run.
     */
    private Date endTime;
    /**
     * The run number.
     */
    private BigDecimal runNumber;

    /**
     * Default ctor.
     */
    public RunInfo() {
    }

    /**
     * @param startTime
     *            the Date
     * @param endTime
     *            the Date
     * @param runNumber
     *            the BigDecimal
     */
    public RunInfo(Date startTime, Date endTime, BigDecimal runNumber) {
        super();
        this.startTime = startTime;
        this.endTime = endTime;
        this.runNumber = runNumber;
    }

    /**
     * @return BigDecimal
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "START_TIME", nullable = false, length = 11)
    public Date getStartTime() {
        return startTime;
    }

    /**
     * @param starttime
     *            the Date
     * @return
     */
    public void setStartTime(Date starttime) {
        this.startTime = starttime;
    }

    /**
     * @return Date
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "END_TIME", nullable = false, length = 11)
    public Date getEndTime() {
        return endTime;
    }

    /**
     * @param endtime
     *            the Date
     * @return
     */
    public void setEndTime(Date endtime) {
        this.endTime = endtime;
    }

    /**
     * @return BigDecimal
     */
    @Id
    @Column(name = "RUN_NUMBER", nullable = false, precision = 38, scale = 0)
    public BigDecimal getRunNumber() {
        return runNumber;
    }

    /**
     * @param run
     *            the BigDecimal
     * @return
     */
    public void setRunNumber(BigDecimal run) {
        this.runNumber = run;
    }

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return "RunInfo [startTime=" + startTime + ", endTime=" + endTime + ", runNumber="
                + runNumber + "]";
    }

}
