package hep.crest.data.runinfo.pojo;
// Generated Aug 2, 2016 3:50:25 PM by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.PrePersist;
import javax.persistence.Table;

import hep.crest.data.config.DatabasePropertyConfigurator;

/**
 * GlobalTag generated by hbm2java.
 */
@Entity
@Table(name = "RUN_LUMI_INFO", schema = DatabasePropertyConfigurator.SCHEMA_NAME)
public class RunLumiInfo implements java.io.Serializable {

    /**
     * Serializer.
     */
    private static final long serialVersionUID = 2748272207787384292L;
    /**
     * The since time.
     */
    private BigDecimal since;
    /**
     * The start time of this run.
     */
    private BigDecimal starttime;
    /**
     * The end time of this run.
     */
    private BigDecimal endtime;
    /**
     * The run number.
     */
    private BigDecimal runNumber;
    /**
     * The lumi block.
     */
    private BigDecimal lb;
    /**
     * The insertion time.
     */
    private Date insertionTime;

    /**
     * Default ctor.
     */
    public RunLumiInfo() {
    }

    /**
     * @param since
     *            the BigDecimal
     * @param starttime
     *            the BigDecimal
     * @param endtime
     *            the BigDecimal
     * @param run
     *            the BigDecimal
     * @param lb
     *            the BigDecimal
     */
    public RunLumiInfo(BigDecimal since, BigDecimal starttime, BigDecimal endtime, BigDecimal run,
            BigDecimal lb) {
        super();
        this.since = since;
        this.starttime = starttime;
        this.endtime = endtime;
        this.runNumber = run;
        this.lb = lb;
    }

    /**
     * @return BigDecimal
     */
    @Id
    @Column(name = "SINCE", nullable = false, precision = 38, scale = 0)
    public BigDecimal getSince() {
        return since;
    }

    /**
     * @param since
     *            the BigDecimal
     * @return
     */
    public void setSince(BigDecimal since) {
        this.since = since;
    }

    /**
     * @return BigDecimal
     */
    @Column(name = "START_TIME", nullable = false, precision = 38, scale = 0)
    public BigDecimal getStarttime() {
        return starttime;
    }

    /**
     * @param starttime
     *            the BigDecimal
     * @return
     */
    public void setStarttime(BigDecimal starttime) {
        this.starttime = starttime;
    }

    /**
     * @return BigDecimal
     */
    @Column(name = "END_TIME", nullable = false, precision = 38, scale = 0)
    public BigDecimal getEndtime() {
        return endtime;
    }

    /**
     * @param endtime
     *            the BigDecimal
     * @return
     */
    public void setEndtime(BigDecimal endtime) {
        this.endtime = endtime;
    }

    /**
     * @return BigDecimal
     */
    @Column(name = "RUN", nullable = false, precision = 38, scale = 0)
    public BigDecimal getRunNumber() {
        return runNumber;
    }

    /**
     * @param run
     *            the BigDecimal
     * @return
     */
    public void setRunNumber(BigDecimal run) {
        this.runNumber = run;
    }

    /**
     * @return BigDecimal
     */
    @Column(name = "LUMI_BLOCK", nullable = false, precision = 38, scale = 0)
    public BigDecimal getLb() {
        return lb;
    }

    /**
     * @param lb
     *            the BigDecimal
     * @return
     */
    public void setLb(BigDecimal lb) {
        this.lb = lb;
    }

    /**
     * @return Date
     */
    public Date getInsertionTime() {
        return insertionTime;
    }

    /**
     * @param insertionTime
     *            the Date
     * @return
     */
    public void setInsertionTime(Date insertionTime) {
        this.insertionTime = insertionTime;
    }

    /**
     * Before saving.
     * 
     * @return
     */
    @PrePersist
    public void prePersist() {
        if (this.getInsertionTime() == null) {
            final Timestamp now = new Timestamp(new Date().getTime());
            this.setInsertionTime(now);
        }
    }

    /*
     * (non-Javadoc)
     *
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return "RunLumiInfo [since=" + since + ", starttime=" + starttime + ", endtime=" + endtime
                + ", run=" + runNumber + ", lb=" + lb + ", insertionTime=" + insertionTime + "]";
    }
}
