package hep.crest.data.runinfo.pojo;
// Generated Aug 2, 2016 3:50:25 PM by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.PrePersist;
import javax.persistence.Table;

import hep.crest.data.config.DatabasePropertyConfigurator;


/**
 * GlobalTag generated by hbm2java
 */
@Entity
@Table(name = "RUN_LUMI_INFO", schema = DatabasePropertyConfigurator.SCHEMA_NAME)
public class RunLumiInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2748272207787384292L;
	/**
	* 
	*/
	private BigDecimal since;
	private BigDecimal starttime;
	private BigDecimal endtime;
	private BigDecimal run;
	private BigDecimal lb;
	private Date insertionTime;

	public RunLumiInfo() {
	}

	public RunLumiInfo(BigDecimal since, BigDecimal starttime, BigDecimal endtime, BigDecimal run, BigDecimal lb) {
		super();
		this.since = since;
		this.starttime = starttime;
		this.endtime = endtime;
		this.run = run;
		this.lb = lb;
	}

	@Id
	@Column(name = "SINCE", nullable = false, precision = 38, scale = 0)
	public BigDecimal getSince() {
		return since;
	}

	public void setSince(BigDecimal since) {
		this.since = since;
	}

	@Column(name = "START_TIME", nullable = false, precision = 38, scale = 0)
	public BigDecimal getStarttime() {
		return starttime;
	}

	public void setStarttime(BigDecimal starttime) {
		this.starttime = starttime;
	}

	@Column(name = "END_TIME", nullable = false, precision = 38, scale = 0)
	public BigDecimal getEndtime() {
		return endtime;
	}

	public void setEndtime(BigDecimal endtime) {
		this.endtime = endtime;
	}

	@Column(name = "RUN", nullable = false, precision = 38, scale = 0)
	public BigDecimal getRun() {
		return run;
	}

	public void setRun(BigDecimal run) {
		this.run = run;
	}

	@Column(name = "LUMI_BLOCK", nullable = false, precision = 38, scale = 0)
	public BigDecimal getLb() {
		return lb;
	}

	public void setLb(BigDecimal lb) {
		this.lb = lb;
	}

	
	public Date getInsertionTime() {
		return insertionTime;
	}

	public void setInsertionTime(Date insertionTime) {
		this.insertionTime = insertionTime;
	}

	@PrePersist
	public void prePersist() {
		if (this.getInsertionTime() == null) {
			Timestamp now = new Timestamp(new Date().getTime());
			this.setInsertionTime(now);
		}
	}

	@Override
	public String toString() {
		return "RunLumiInfo [since=" + since + ", starttime=" + starttime + ", endtime=" + endtime + ", run=" + run
				+ ", lb=" + lb + ", insertionTime=" + insertionTime + "]";
	}

}
