caching:
    iovsgroups_maxage: 600
    iovsgroups_snapshot_maxage: 3600
    iovs_maxage: 600
    iovs_snapshot_maxage: 3600
    payloads_maxage: 604800
    timetype_groupsize: 86400  # expressed in seconds: 3600*24
    runtype_groupsize: 100    # expressed in run numbers
crest:
    audience: https://crest/api
spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: https://dev-andrea-1971.eu.auth0.com/
        strategy: MODE_INHERITABLETHREADLOCAL
