# ===============================
# = PROFILES /
#             server
#             ...
# ===============================
# Defaults
spring:
 profiles:
  include: default
crest:
  dbfile: /tmp/crestdbsqlite
  authenticationtype: database
server:
    port: 8090
    servlet-path: /
spring:
    profiles: sqlite
    jersey:
      application-path: /crestapi
    datasource:
      url: jdbc:sqlite:${crest.dbfile}
      driverClassName: org.sqlite.JDBC
      username: 
      password:
    jpa:
      properties:
        hibernate.dialect: org.hibernate.dialect.SQLiteDialect
        hibernate.jdbc.fetch_size: 100
        hibernate.hbm2ddl.auto: update
        hibernate.show_sql: false
