# ===============================
# = PROFILES /
#             datasources
#             ...
# ===============================
# Defaults
crest:
  dumpdir: /tmp
  schemaname: none
  security: none
  synchro: none
  webstaticdir: /tmp
  dbfile: /tmp/crestdbh2
  apiname: /crestapi
  authenticationtype: none
spring:
    security.strategy: MODE_INHERITABLETHREADLOCAL
    jersey:
      application-path: /crestapi
    datasource:
      url: jdbc:h2:/tmp/cresth2web;DB_CLOSE_ON_EXIT=FALSE
      driverClassName: org.h2.Driver
      username: root
      password: root
      hikari:
        connection-test-query: SELECT 1 
        maximum-pool-size: 1
    jpa:
      properties:
        hibernate.dialect: org.hibernate.dialect.H2Dialect
        hibernate.jdbc.fetch_size: 100
        hibernate.hbm2ddl.auto: update
        hibernate.show_sql: false
    
info:
  app:
    name: Crest Application
    description: Rest services for conditions data management 
    profile: default
    
      
