# ===============================
# = PROFILES /
#             server
#             ...
# ===============================
# Defaults
spring:
 profiles:
  include: default
spring:
    profiles: mysql
    jersey:
      application-path: /crestapi
    datasource:
      url: jdbc:mysql://localhost:${crest.db.port}/crestdb
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: 
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        connection-test-query: SELECT 1 FROM DUAL
        maximum-pool-size: 20
    jpa:
      properties:
        hibernate.dialect: org.hibernate.dialect.MySQLDialect
        hibernate.jdbc.fetch_size: 300
# This should be changed for production to "validate"
        hibernate.hbm2ddl.auto: create
        hibernate.show_sql: false
        hibernate.jdbc.use_streams_for_binary: false
        hibernate.connection.autocommit: false
        hibernate.default_schema: crestdb
        hibernate.globally_quoted_identifiers: true
server:
    port: 8080 
crest:
  schemaname: none
  dump_dir: ${crest.dump.dir}
  webstaticdir: ${crest.web.static}
  dump_dir: /tmp
  db:
    port: 3306
