# ===============================
# = PROFILES /
#             server
#             ...
# ===============================
# schemaname : ATLAS_PHYS_COND or none
# security options: reco (no POST allowed), weak (no authentication needed), active (GET and POST requires roles)
server:
    port: 8090
    servlet.path: /    
    connection-timeout: 60s
spring:
    profiles:
      include: crest
    security:
      strategy: MODE_INHERITABLETHREADLOCAL
    jersey:
      application-path: ${crest.api.name}
    datasource:
      jdbc-url: jdbc:h2:${crest.dbfile};DB_CLOSE_ON_EXIT=FALSE
      driverClassName: org.h2.Driver
      username: root
      password: root
      type: com.zaxxer.hikari.HikariDataSource
      hikari: 
        connection-test-query: SELECT 1 
        maximum-pool-size: 3
    jpa:
      properties:
        hibernate.dialect: org.hibernate.dialect.H2Dialect
        hibernate.jdbc.fetch_size: 100
        hibernate.hbm2ddl.auto: update
        hibernate.show_sql: false
info:
  app:
    name: Crest Application
    description: Rest services for conditions data management 
    profile: default
crest:
  dumpdir: /tmp
  schemaname: none
  security: ${crest.server.security}
  synchro: none
  webstaticdir: /tmp
  dbfile: /tmp/crestdbh2
  apiname: ${crest.api.name}
  authenticationtype: none

    