# ===============================
# = PROFILES /
#             server
#             ...
# ===============================
# Defaults
caching:
  iovsgroups_maxage: 600
  iovsgroups_snapshot_maxage: 3600
  iovs_maxage: 600
  iovs_snapshot_maxage: 3600
  payloads_maxage: 604800
  timetype_groupsize: 3600  # expressed in seconds
  runtype_groupsize: 100    # expressed in run numbers

# schemaname : ATLAS_PHYS_COND or none
# security options: reco (no POST allowed), weak (no authentication needed), active (GET and POST requires roles)
crest:
  dumpdir: /tmp
  schemaname: none
  security: none
  synchro: none
  webstaticdir: /tmp/data/web
  dbfile: /tmp/crestdbh2
  authenticationtype: none
  
server:
    port: 8090
    servlet.path: /    
    connection-timeout: 60s
spring:
    security.strategy: MODE_INHERITABLETHREADLOCAL
    jersey:
      application-path: /crestapi
    datasource:
      url: jdbc:h2:${crest.dbfile};DB_CLOSE_ON_EXIT=FALSE
      driverClassName: org.h2.Driver
      username: root
      password: root
      type: com.zaxxer.hikari.HikariDataSource
      hikari: 
        connection-test-query: SELECT 1 
        maximum-pool-size: 3
    jpa:
      properties:
        hibernate.dialect: org.hibernate.dialect.H2Dialect
        hibernate.jdbc.fetch_size: 100
        hibernate.hbm2ddl.auto: update
        hibernate.show_sql: false
    
info:
  app:
    name: Crest Application
    description: Rest services for conditions data management 
    profile: default
    
    