# ===============================
# = PROFILES /
#             server
#             ...
# ===============================
# Defaults
spring:
 profiles:
  include: default
spring:
    profiles: prod
    jersey:
      application-path: /crestapi
    datasource:
      url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=cman1-atlas.cern.ch)(PORT=10500))(LOAD_BALANCE=on)(ENABLE=BROKEN)(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=intr.cern.ch)))
      driverClassName: oracle.jdbc.OracleDriver
      username: ATLAS_PHYS_COND_W
      password: ${crest.db.password}
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        connection-test-query: SELECT 1 FROM DUAL
        maximum-pool-size: 20
    jpa:
      properties:
        hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
        hibernate.jdbc.fetch_size: 100
        hibernate.hbm2ddl.auto: validate
        hibernate.show_sql: false
        hibernate.default_schema: ATLAS_PHYS_COND
server:
    port: 8080 
crest:
  schemaname: ATLAS_PHYS_COND  
  webstaticdir: ${crest.web.static}
  dumpdir: ${crest.dump.dir}
  security: none
  synchro: none
  authenticationtype: none
  
info:
  app:
    name: Crest Application
    description: Rest services for conditions data management 
    profile: prod
    

