package hep.crest.server.swagger.impl;

import jakarta.ws.rs.core.UriInfo;
import org.springframework.stereotype.Component;
import org.springframework.web.context.annotation.RequestScope;

import jakarta.servlet.http.HttpServletRequest;
import jakarta.ws.rs.core.HttpHeaders;
import jakarta.ws.rs.core.Request;

/**
 * A request scoped holder object of the JAX/RS context.
 * Need to be set in the API methods generated by openApi.
 * You should add the following to the Api classes and methods where you want this context.
 *  On top of the Api class:
 *  @Context
 *  protected Request request;
 *  @Context
 *  protected HttpHeaders headers;
 *  @Autowired
 *  protected JAXRSContext context;
 *
 *  Inside the method, before calling the delegate:
 *  context.setHttpHeaders(headers);
 *  context.setRequest(request);
 */
@Component
@RequestScope
public class JAXRSContext {

    /**
     * Request from context.
     */
    private Request request = null;
    /**
     * Headers from context.
     */
    private HttpHeaders httpHeaders = null;

    /**
     * Servlet request from context.
     */
    private HttpServletRequest httpServletRequest = null;
    /**
     * The URI info.
     */
    private UriInfo uriInfo = null;

    /**
     * The Request to get.
     * @return Request
     */
    public Request getRequest() {
        return request;
    }

    /**
     * The request to set.
     * @param request
     */
    public void setRequest(Request request) {
        this.request = request;
    }

    /**
     * The headers to get.
     * @return httpHeaders
     */
    public HttpHeaders getHttpHeaders() {
        return httpHeaders;
    }

    /**
     * The headers to set.
     * @param httpHeaders
     */
    public void setHttpHeaders(HttpHeaders httpHeaders) {
        this.httpHeaders = httpHeaders;
    }

    /**
     *
     * @return HttpServletRequest
     */
    public HttpServletRequest getHttpServletRequest() {
        return httpServletRequest;
    }

    /**
     * The HttpServletRequest to set.
     * @param httpServletRequest
     */
    public void setHttpServletRequest(HttpServletRequest httpServletRequest) {
        this.httpServletRequest = httpServletRequest;
    }

    /**
     * The URI info to get.
     * @return UriInfo
     */
    public UriInfo getUriInfo() {
        return uriInfo;
    }

    /**
     * The URI info to set.
     * @param uriInfo
     */
    public void setUriInfo(UriInfo uriInfo) {
        this.uriInfo = uriInfo;
    }
}