# coding: utf-8

"""
    CrestDB REST API

    Crest Rest Api to manage data for calibration files.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: andrea.formica@cern.ch
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class IovPayloadDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'since': 'float',
        'payload': 'str'
    }

    attribute_map = {
        'since': 'since',
        'payload': 'payload'
    }

    def __init__(self, since=None, payload=None):  # noqa: E501
        """IovPayloadDto - a model defined in Swagger"""  # noqa: E501

        self._since = None
        self._payload = None
        self.discriminator = None

        if since is not None:
            self.since = since
        if payload is not None:
            self.payload = payload

    @property
    def since(self):
        """Gets the since of this IovPayloadDto.  # noqa: E501


        :return: The since of this IovPayloadDto.  # noqa: E501
        :rtype: float
        """
        return self._since

    @since.setter
    def since(self, since):
        """Sets the since of this IovPayloadDto.


        :param since: The since of this IovPayloadDto.  # noqa: E501
        :type: float
        """

        self._since = since

    @property
    def payload(self):
        """Gets the payload of this IovPayloadDto.  # noqa: E501


        :return: The payload of this IovPayloadDto.  # noqa: E501
        :rtype: str
        """
        return self._payload

    @payload.setter
    def payload(self, payload):
        """Sets the payload of this IovPayloadDto.


        :param payload: The payload of this IovPayloadDto.  # noqa: E501
        :type: str
        """

        self._payload = payload

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IovPayloadDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IovPayloadDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
