# ===============================
# = PROFILES /
#             datasources
#             ...
# ===============================
# Defaults
crest:
  dump_dir: /tmp
  schemaname: none
  security: none
  synchro: none
  webstaticdir: /tmp
  dbfile: /tmp/cresth2
spring:
    datasource:
      url: jdbc:h2:/tmp/cresth2test;DB_CLOSE_ON_EXIT=FALSE
      driverClassName: org.h2.Driver
      username: root
      password: root
      hikari:
        connection-test-query: SELECT 1 
        maximum-pool-size: 1
      
