# coding: utf-8

"""
    CrestDB REST API

    Crest Rest Api to manage data for calibration files.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: andrea.formica@cern.ch
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import crestapi
from crestapi.api.fs_api import FsApi  # noqa: E501
from crestapi.rest import ApiException


class TestFsApi(unittest.TestCase):
    """FsApi unit test stubs"""

    def setUp(self):
        self.api = crestapi.api.fs_api.FsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_build_tar(self):
        """Test case for build_tar

        Dump a tag into filesystem and retrieve the tar file asynchronously.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
