# coding: utf-8

"""
    CrestDB REST API

    Crest Rest Api to manage data for calibration files.

    OpenAPI spec version: 2.0
    Contact: andrea.formica@cern.ch
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import crestapi
from crestapi.rest import ApiException
from crestapi.apis.runinfo_api import RuninfoApi


class TestRuninfoApi(unittest.TestCase):
    """ RuninfoApi unit test stubs """

    def setUp(self):
        self.api = crestapi.apis.runinfo_api.RuninfoApi()

    def tearDown(self):
        pass

    def test_create_run_lumi_info(self):
        """
        Test case for create_run_lumi_info

        Create an entry for run information.
        """
        pass

    def test_list_run_lumi_info(self):
        """
        Test case for list_run_lumi_info

        Finds a RunLumiInfoDto lists.
        """
        pass


if __name__ == '__main__':
    unittest.main()
