# coding: utf-8

"""
    CrestDB REST API

    Crest Rest Api to manage data for calibration files.

    OpenAPI spec version: 2.0
    Contact: andrea.formica@cern.ch
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import crestapi
from crestapi.rest import ApiException
from crestapi.apis.tags_api import TagsApi


class TestTagsApi(unittest.TestCase):
    """ TagsApi unit test stubs """

    def setUp(self):
        self.api = crestapi.apis.tags_api.TagsApi()

    def tearDown(self):
        pass

    def test_create_tag(self):
        """
        Test case for create_tag

        Create a Tag in the database.
        """
        pass

    def test_find_tag(self):
        """
        Test case for find_tag

        Finds a TagDto by name
        """
        pass

    def test_list_tags(self):
        """
        Test case for list_tags

        Finds a TagDtos lists.
        """
        pass

    def test_update_tag(self):
        """
        Test case for update_tag

        Update a TagDto by name
        """
        pass


if __name__ == '__main__':
    unittest.main()
