# coding: utf-8

"""
    CrestDB REST API

    Crest Rest Api to manage data for calibration files.

    OpenAPI spec version: 2.0
    Contact: andrea.formica@cern.ch
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import crestapi
from crestapi.rest import ApiException
from crestapi.apis.globaltags_api import GlobaltagsApi


class TestGlobaltagsApi(unittest.TestCase):
    """ GlobaltagsApi unit test stubs """

    def setUp(self):
        self.api = crestapi.apis.globaltags_api.GlobaltagsApi()

    def tearDown(self):
        pass

    def test_create_global_tag(self):
        """
        Test case for create_global_tag

        Create a GlobalTag in the database.
        """
        pass

    def test_find_global_tag(self):
        """
        Test case for find_global_tag

        Finds a GlobalTagDto by name
        """
        pass

    def test_find_global_tag_fetch_tags(self):
        """
        Test case for find_global_tag_fetch_tags

        Finds a TagDtos lists associated to the global tag name in input.
        """
        pass

    def test_list_global_tags(self):
        """
        Test case for list_global_tags

        Finds a GlobalTagDtos lists.
        """
        pass


if __name__ == '__main__':
    unittest.main()
