# coding: utf-8

"""
    CrestDB REST API

    Crest Rest Api to manage data for calibration files.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: andrea.formica@cern.ch
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import crestapi
from crestapi.api.monitoring_api import MonitoringApi  # noqa: E501
from crestapi.rest import ApiException


class TestMonitoringApi(unittest.TestCase):
    """MonitoringApi unit test stubs"""

    def setUp(self):
        self.api = crestapi.api.monitoring_api.MonitoringApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_payload_tag_info(self):
        """Test case for list_payload_tag_info

        Retrieves monitoring information on payload as a list of PayloadTagInfoDtos.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
