# coding: utf-8

"""
    CrestDB REST API

    Crest Rest Api to manage data for calibration files.

    OpenAPI spec version: 2.0
    Contact: andrea.formica@cern.ch
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import crestapi
from crestapi.rest import ApiException
from crestapi.apis.payloads_api import PayloadsApi


class TestPayloadsApi(unittest.TestCase):
    """ PayloadsApi unit test stubs """

    def setUp(self):
        self.api = crestapi.apis.payloads_api.PayloadsApi()

    def tearDown(self):
        pass

    def test_create_payload(self):
        """
        Test case for create_payload

        Create a Payload in the database.
        """
        pass

    def test_create_payload_multi_form(self):
        """
        Test case for create_payload_multi_form

        Create a Payload in the database.
        """
        pass

    def test_get_blob(self):
        """
        Test case for get_blob

        Finds payload data by hash; the payload object contains the real BLOB.
        """
        pass

    def test_get_payload(self):
        """
        Test case for get_payload

        Finds a payload resource associated to the hash.
        """
        pass

    def test_get_payload_meta_info(self):
        """
        Test case for get_payload_meta_info

        Finds a payload resource associated to the hash.
        """
        pass


if __name__ == '__main__':
    unittest.main()
