# coding: utf-8

"""
    CrestDB REST API

    Crest Rest Api to manage data for calibration files.

    OpenAPI spec version: 2.0
    Contact: andrea.formica@cern.ch
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import crestapi
from crestapi.rest import ApiException
from crestapi.models.generic_map import GenericMap


class TestGenericMap(unittest.TestCase):
    """ GenericMap unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGenericMap(self):
        """
        Test GenericMap
        """
        model = crestapi.models.generic_map.GenericMap()


if __name__ == '__main__':
    unittest.main()
