# coding: utf-8

"""
    CrestDB REST API

    Crest Rest Api to manage data for calibration files.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: andrea.formica@cern.ch
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import crestapi
from crestapi.models.payload_tag_info_dto import PayloadTagInfoDto  # noqa: E501
from crestapi.rest import ApiException


class TestPayloadTagInfoDto(unittest.TestCase):
    """PayloadTagInfoDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPayloadTagInfoDto(self):
        """Test PayloadTagInfoDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = crestapi.models.payload_tag_info_dto.PayloadTagInfoDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
